update=Sun 23 Mar 2014 20:12:19 GMT
last_client=pcbnew
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
PadDrlX=472
PadDimH=709
PadDimV=709
BoardThickness=630
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=150
LastNetListRead=nes_blow_cart.net
[pcbnew/libraries]
LibDir=
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=led
LibName9=dip_sockets
LibName10=pga_sockets
LibName11=valves
LibName12=/home/facelessloser/Dropbox/kicad/my_stuff/Sound_sensor
LibName13=/home/facelessloser/Dropbox/kicad/my_stuff/NBC_post
LibName14=/home/facelessloser/Dropbox/kicad/my_stuff/6_PIN_BREAKOUT
LibName15=/home/facelessloser/Dropbox/kicad/my_stuff/OSH_final_silks_back
LibName16=/home/facelessloser/Dropbox/kicad/one_button_remote/OSH_logo
